
services:
  bot:
    build: .
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_TOKEN2=${TELEGRAM_BOT_TOKEN2}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    env_file:
      - .env
    ports:
      - "8080:8000"
    networks:
      default:
        driver: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4