version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - TELEGRAM_TOKEN=7319059348:AAGbP4qCmCusVfq4oyDPP_eNksAw2jSqe0g
    ports:
      - "8000:8000" # Если необходимо
