version: '3.8'

services:
  bot:
    build: .
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN2}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    env_file:
      - .env
    ports:
      - "8000:8000" # Если необходимо
